### ISSUE TITLE
Getting errors when used with launchpad and websiteProvider

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/Search#19]
### Involved apps:

- Signin 5.3.0
- Launchpad 1.1.1
- WebsiteProvider 2.1.0 
- Search 1.0.0

### Steps to reproduce:

1. checkout the involved apps or download the latest versions from the Apps Warehouse.
2. Go to localhost:8080/Launchpad
3. Click on Search icon
4. Type something to search and hit `ENTER` (don't select any item from the result list if any shows up)
5. click on launchpad Icon from top left corner

__you will get the following Exception:__

`Starcounter.XSON.JsonPatchException: Unknown property in path. Patch: '{"op":"replace","path":"/WebsiteProvider_0/Sections/Main/MainContent/Search_0/CurrentPage/Search_0/HideSuggestions$","value":2}'. Property: 'HideSuggestions$'. Viewmodel versions: {client (_ver#c$): 7, clients serverversion: 8, server (_ver#s): 8}.
   at Starcounter.XSON.JsonProperty.EvalutateCurrent(ViewModelVersion version) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 172
   at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 69
   at Starcounter.XSON.JsonProperty.DoEvaluate(Json root) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 88
   at Starcounter.XSON.JsonProperty.Evaluate(JsonPointer pointer, Json root) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonProperty.cs:line 62
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 19
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 550
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 478
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 376
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
Patch={"op":"replace","path":"/WebsiteProvider_0/Sections/Main/MainContent/Search_0/CurrentPage/Search_0/HideSuggestions$","value":2}
CurrentProperty=HideSuggestions$
Severity=1
HResult=-2146233088`

**Comment by bouguila** [comment]
ping @habib535

**Comment by habib535** [comment]
This is fixed and the updated version is deployed to warehouse.
